baseURL: "/"
languageCode: "en-us"
title: "Tristan B. Kildaire"
theme: "the-theme"
 
relativeURLs: true

menu:
  main:
    - name: Home
      url: "/"
      weight: 1
        
    - name: Projects
      url: "projects/"
      weight: 2

    - name: Blog
      url: "blog/"
      weight: 3

    - name: Hot takes
      url: "hottakes/"
      weight: 4

    - name: Offers
      url: "services/"
      weight: 5
      
    - name: Work
      url: "work/"
      weight: 6

    - name: Research
      url: "research/"
      weight: 7

    - name: About
      url: "about/"
      weight: 8
