baseURL: "/"
languageCode: "en-us"
title: "Tristan B. Kildaire"
theme: "the-theme"
 
relativeURLs: true

menu:
  main:
    - name: Home
      url: "/"
      weight: 1
        
    - name: Projects
      url: "projects/"
      weight: 2

    - name: Blog
      url: "blog/"
      weight: 3

    - name: Offers
      url: "services/"
      weight: 4
      
    - name: Work
      url: "work/"
      weight: 5

    - name: Research
      url: "research/"
      weight: 6

    - name: About
      url: "about/"
      weight: 7

# markup:
  # goldmark:
    # extensions:
      # passthrough:
        # enable: true
        # delimiters:
          # block: [['\[', '\]'], ['$$', '$$']]
          # inline: [['\(', '\)']]
# params:
  # math: true
